In [9]:
#Q-1 CAA WITH THE HELP OF LIST WITH ALL ELEMENT AS FLOAT
import numpy as np
plist = [1, 2, 3, 4, 5]
farray = np.array(plist, dtype=float)
print(farray)

[1. 2. 3. 4. 5.]


In [10]:
#Q-2 CAA WITH THE HELP OF ONES WITH 5 ROWS AND 6 COLUMNS 
a=np.ones((5,6))
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [11]:
#Q-3 CAA WITH HELP OF FULL WITH 4 ROWS AND 5 COLUMNS AND VALUE AS 66.67
a=np.full((4,5),66.67)
print(a)

[[66.67 66.67 66.67 66.67 66.67]
 [66.67 66.67 66.67 66.67 66.67]
 [66.67 66.67 66.67 66.67 66.67]
 [66.67 66.67 66.67 66.67 66.67]]


In [12]:
#Q-4 CAA WITH LINSPACE WITH EQUAL SPACING OF 2
a = np.linspace(2, 20, 10)
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [13]:
#Q-5 CAA WITH HELP OF ARANGE WITHH STEP OF 4
a=np.arange(1,30,4)
print(a)

[ 1  5  9 13 17 21 25 29]


In [14]:
#Q-6 CAA WITH HELP OF RANDOM FUNCTION WITH 20 RANDOM VALUES B/W 10 & 11
a=np.random.random(20) +10
print(a)

[10.12229836 10.18955791 10.83015545 10.27455927 10.70111775 10.24606397
 10.12656909 10.46743177 10.68754649 10.69068618 10.46505647 10.94957988
 10.10581193 10.65035323 10.83718886 10.85930016 10.12213124 10.29601914
 10.42099172 10.70403744]


In [15]:
#Q-7 CAA WITH HELP OF RANDOMINT B/W 10 & 40
a=np.random.randint(10,40)
print(a)

22
